// src/components/LoadingScreen.vue
<template>
  <Transition name="fade">
    <div
      v-if="isLoading"
      class="fixed inset-0 z-[100] bg-[#0b1326] flex flex-col items-center justify-center"
    >
      <div class="relative mb-8">
        <div class="w-20 h-20 border-4 border-[#2d3449] rounded-full animate-spin-slow border-t-[#4be277]" />
        <div class="absolute inset-0 flex items-center justify-center">
          <img src="/Icono.png" alt="Logo" class="w-8 h-8 object-contain" />
        </div>
      </div>
      <p class="font-mono text-sm text-[#4be277] animate-pulse">Loading...</p>
    </div>
  </Transition>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const isLoading = ref(true)

onMounted(() => {
  const timer = setTimeout(() => { isLoading.value = false }, 1500)
  window.addEventListener('load', () => {
    setTimeout(() => { isLoading.value = false }, 300)
  }, { once: true })
  return () => clearTimeout(timer)
})
</script>

<style scoped>
.fade-leave-active { transition: opacity 0.5s ease; }
.fade-leave-to    { opacity: 0; }
</style>

// app/components/LoadingScreen.tsx
"use client";
import { useState, useEffect } from "react";
import Image from "next/image";

export default function LoadingScreen() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 1500);

    window.addEventListener("load", () => {
      setTimeout(() => setIsLoading(false), 300);
    });

    return () => clearTimeout(timer);
  }, []);

  if (!isLoading) return null;

  return (
    <div className="fixed inset-0 z-[100] bg-[#0b1326] flex flex-col items-center justify-center">
      {/* Círculo giratorio con logo centrado */}
      <div className="relative mb-8">
        <div className="w-20 h-20 border-4 border-[#2d3449] rounded-full animate-spin border-t-[#4be277]" />
        <div className="absolute inset-0 flex items-center justify-center">
          <Image
            src="/icono.png"
            alt="Logo"
            width={32}
            height={32}
            className="object-contain"
          />
        </div>
      </div>

      {/* Texto de carga */}
      <p className="font-mono text-sm text-[#4be277] animate-pulse">
        Loading...
      </p>
    </div>
  );
}
