// app/components/ScrollProgress.tsx
"use client";
import { useState, useEffect } from "react";

export default function ScrollProgress() {
  const [scrollProgress, setScrollProgress] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      const totalScroll = document.documentElement.scrollHeight - window.innerHeight;
      const currentProgress = (window.scrollY / totalScroll) * 100;
      setScrollProgress(currentProgress);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className="fixed top-0 left-0 w-full h-1 z-[60]">
      <div
        className="h-full bg-gradient-to-r from-[#4be277] to-[#22c55e] transition-all duration-200"
        style={{ width: `${scrollProgress}%` }}
      />
    </div>
  );
}

// src/components/ScrollProgress.vue
<template>
  <div class="fixed top-0 left-0 w-full h-1 z-[60]">
    <div
      class="h-full bg-gradient-to-r from-[#4be277] to-[#22c55e] transition-all duration-200"
      :style="{ width: scrollProgress + '%' }"
    />
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

const scrollProgress = ref(0)

function handleScroll() {
  const total = document.documentElement.scrollHeight - window.innerHeight
  scrollProgress.value = (window.scrollY / total) * 100
}

onMounted(()   => window.addEventListener('scroll', handleScroll))
onUnmounted(() => window.removeEventListener('scroll', handleScroll))
</script>
